### ISSUE TITLE
Duração das Talks

### ISSUE THREAD

**Issue by vinicius0026** [floripajs/meetup#1]
Fala pessoal.

Gostaria de saber qual a duração das talks, por favor.

Valeu! Abs

**Comment by lucasfcosta** [comment]
Opa, tudo bem @vinicius0026?

Para o próximo meetup acredito que deva girar em torno de 30/45 minutos. Mas gostaríamos de testar novos formatos no futuro.

**Comment by vinicius0026** [comment]
Blz! Valeu!
